[project]
name = "lab12"
version = "0.1.0"
description = "Lab 12: Agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-core",
    "langchain-openai",
    "langgraph",
    "rich>=15.0.0",
]

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
